// This file is generated by Slice Machine. Update with care!

import Code from './Code';
import HomePageLink from './HomePageLink';
import Icons from './Icons';
import Image from './Image';
import ImageCaption from './ImageCaption';
import TextBlock from './TextBlock';

export {
	Code,
	HomePageLink,
	Icons,
	Image,
	ImageCaption,
	TextBlock,
};

export const components = {
	code: Code,
	home_page_link: HomePageLink,
	icons: Icons,
	image: Image,
	image_caption: ImageCaption,
	text_block: TextBlock,
};
