// This file is generated by Slice Machine. Update with care!

import ImageCaption from './ImageCaption';
import TextBlock from './TextBlock';
import TextImageRight from './TextImageRight';

export {
	ImageCaption,
	TextBlock,
	TextImageRight,
};

export const components = {
	image_caption: ImageCaption,
	text_block: TextBlock,
	text_image_right: TextImageRight,
};
