// This file is generated by Slice Machine. Update with care!

import TextBlock from './TextBlock';
import TextImageRight from './TextImageRight';

export {
	TextBlock,
	TextImageRight,
};

export const components = {
	text_block: TextBlock,
	text_image_right: TextImageRight,
};
